<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-10-27T21:30:20 IST" name="Default suite" finished-at="2025-10-27T21:30:37 IST" duration-ms="16169">
    <groups>
    </groups>
    <test started-at="2025-10-27T21:30:20 IST" name="Default test" finished-at="2025-10-27T21:30:37 IST" duration-ms="16169">
      <class name="TestLayer.LoginTestPage">
        <test-method is-config="true" signature="setUp()[pri:0, instance:TestLayer.LoginTestPage@515c6049]" started-at="2025-10-27T21:30:20 IST" name="setUp" finished-at="2025-10-27T21:30:26 IST" duration-ms="5633" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLoginPage()[pri:0, instance:TestLayer.LoginTestPage@515c6049]" started-at="2025-10-27T21:30:26 IST" name="validateLoginPage" finished-at="2025-10-27T21:30:33 IST" duration-ms="7148" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home page title not matched, TC failed expected [Magnus1] but found [Magnus]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home page title not matched, TC failed expected [Magnus1] but found [Magnus]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at TestLayer.LoginTestPage.validateLoginPage(LoginTestPage.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestLayer.LoginTestPage@515c6049]" started-at="2025-10-27T21:30:33 IST" name="tearDown" finished-at="2025-10-27T21:30:37 IST" duration-ms="3294" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="add()[pri:0, instance:TestLayer.LoginTestPage@515c6049]" started-at="2025-10-27T21:30:37 IST" name="add" finished-at="2025-10-27T21:30:37 IST" depends-on-methods="TestLayer.LoginTestPage.validateLoginPage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestLayer.LoginTestPage.add() on instance TestLayer.LoginTestPage@515c6049 depends on not successfully finished methods 
[TestLayer.LoginTestPage.validateLoginPage() on instance TestLayer.LoginTestPage@515c6049]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestLayer.LoginTestPage.add() on instance TestLayer.LoginTestPage@515c6049 depends on not successfully finished methods 
[TestLayer.LoginTestPage.validateLoginPage() on instance TestLayer.LoginTestPage@515c6049]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- add -->
      </class> <!-- TestLayer.LoginTestPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
